# Generated by Django 5.0.3 on 2024-04-03 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Área do Saber')),
            ],
            options={
                'verbose_name_plural': 'Áreas do Saber',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Ocupação da Pessoa')),
            ],
            options={
                'verbose_name': 'Ocupação',
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Período')),
            ],
            options={
                'verbose_name_plural': 'Períodos de Cursos',
            },
        ),
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('turno', models.CharField(max_length=100, verbose_name='Turno')),
            ],
            options={
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('carga_hor_total', models.CharField(max_length=100, verbose_name='Carga Horária Total do Curso')),
                ('duracao_meses', models.CharField(max_length=100, verbose_name='Duração em Meses do Curso')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas', verbose_name='Área do Saber')),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Disciplina')),
                ('area_saber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas', verbose_name='Área do Saber')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name_plural': 'Avaliações',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Instituição')),
                ('site', models.CharField(max_length=100, verbose_name='Site da Instituição')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do Usuário')),
            ],
            options={
                'verbose_name': 'Instituição',
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição'),
        ),
        migrations.CreateModel(
            name='Disciplina_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.CharField(max_length=100, verbose_name='Carga Horária do Curso')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('periodos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodos', verbose_name='Período do Curso')),
            ],
            options={
                'verbose_name_plural': 'Disciplinas por Curso',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_pai', models.CharField(max_length=100, verbose_name='Nome do Pai')),
                ('nome_da_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('cpf', models.CharField(max_length=100, verbose_name='CPF do usuário')),
                ('dat_nasc', models.CharField(max_length=100, verbose_name='Data de Nascimento')),
                ('email', models.CharField(max_length=100, verbose_name='Email do Usuário')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Usuário')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidade', verbose_name='Cidade do Usuário')),
                ('ocupacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao', verbose_name='Ocupação do Usuário')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição da Ocorrência')),
                ('data', models.CharField(max_length=100, verbose_name='Data da Ocorrência')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.CharField(max_length=100, verbose_name='Data de Início do Curso')),
                ('data_prev_termino', models.CharField(max_length=100, verbose_name='Data de Término do Curso')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos da Instituição')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao', verbose_name='Instituição do Usuário')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name_plural': 'Matrículas',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_faltas', models.CharField(max_length=100, verbose_name='Número de Faltas')),
                ('cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario', verbose_name='Nome do Usuário')),
            ],
            options={
                'verbose_name': 'Frequência',
            },
        ),
    ]
